### ISSUE TITLE
Not JSON response for waitForElementByXPath

### ISSUE THREAD

**Issue by kamok** [NativeScript/nativescript-dev-appium#137]
Following guide on https://docs.nativescript.org/plugins/ui-tests, starting up basic e2e testing fails on an existing NativeScript Angular application with unit testing set up.

Exact error:
```
1) sample scenario
       should find an element by text:
     [waitForElementByXPath("//*[@label='Login' or @value='Login' or @hint='Login']",5000)] [elements("xpath","//*[@label='Login' or @value='Login' or @hint='Login']")] Not JSON response
  Error: [elements("xpath","//*[@label='Login' or @value='Login' or @hint='Login']")] Not JSON response
      at exports.newError (node_modules/wd/lib/utils.js:148:13)
      at /Users/kamok/code/organizing-mobile/InternalOrganizing/node_modules/wd/lib/callbacks.js:78:17
      at /Users/kamok/code/organizing-mobile/InternalOrganizing/node_modules/wd/lib/webdriver.js:185:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

### Which platform(s) does your issue occur on?
iOS emulator via `npm run e2e -- --runType sim.iPhone6 --reuseDevice`

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) `4.1.0`
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) `4.1.0`
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
```
    "tns-ios": {
      "version": "4.1.0"
    },
    "tns-android": {
      "version": "4.1.3"
    }
```
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
```
 "dependencies": {
    "@angular/animations": "~6.0.0",
    "@angular/common": "~6.0.0",
    "@angular/compiler": "~6.0.0",
    "@angular/core": "~6.0.0",
    "@angular/forms": "~6.0.0",
    "@angular/http": "~6.0.0",
    "@angular/platform-browser": "~6.0.0",
    "@angular/platform-browser-dynamic": "~6.0.0",
    "@angular/router": "~6.0.0",
    "@ngxs/form-plugin": "^3.1.4",
    "@ngxs/store": "^3.1.4",
    "jasmine": "^3.1.0",
    "nativescript-angular": "~6.0.0",
    "nativescript-cardview": "^3.1.1",
    "nativescript-localize": "^3.0.4",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-sidedrawer": "^4.1.1",
    "nativescript-unit-test-runner": "^0.3.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~6.1.0",
    "tns-core-modules": "~4.1.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@types/chai": "^4.1.4",
    "@types/jasmine": "^2.8.8",
    "@types/mocha": "^5.2.5",
    "@types/node": "^7.0.5",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "jasmine-core": "^3.1.0",
    "karma": "^2.0.2",
    "karma-jasmine": "^1.1.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-appium": "^4.0.2",
    "nativescript-dev-sass": "^1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "tslint": "^5.10.0",
    "tslint-angular": "^1.1.2",
    "typescript": "~2.7.2"
  }
```
### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
`npm run e2e -- --runType sim.iPhone6 --reuseDevice`
### Is there any code involved? 
```
describe('sample scenario', () => {
  let driver: AppiumDriver;

  before(async () => {
    driver = await createDriver();
  });

  after(async () => {
    await driver.quit();
  });

  // afterEach(async () => {
  //   if (this.currentTest.state === 'failed') {
  //     await driver.logTestArtifacts(this.currentTest.title);
  //   }
  // });

  it('should find an element by text', async () => {
    const submitBtn = await driver.findElementByText('Login');
    const submitBtnText = await submitBtn.text();
    assert.equal(submitBtnText, 'Login');
  });
});
```
`this.currentTest` is returning undefined so I commented it out, don't know if it's related.

Full log:

```
  0 passing (2m)
  1 failing

  1) sample scenario
       should find an element by text:
     [waitForElementByXPath("//*[@label='Login' or @value='Login' or @hint='Login']",5000)] [elements("xpath","//*[@label='Login' or @value='Login' or @hint='Login']")] Not JSON response
  Error: [elements("xpath","//*[@label='Login' or @value='Login' or @hint='Login']")] Not JSON response
      at exports.newError (node_modules/wd/lib/utils.js:148:13)
      at /Users/kamok/code/organizing-mobile/InternalOrganizing/node_modules/wd/lib/callbacks.js:78:17
      at /Users/kamok/code/organizing-mobile/InternalOrganizing/node_modules/wd/lib/webdriver.js:185:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by kamok** [comment]
You need `brew install carthage`.

Please update your tutorials, especially that blog post.

**Comment by SvetoslavTsenov** [comment]
Hey @kamok, thank you for your feedback. We are currently preparing some changes related to documentation and will try to make this more clearer.
Anyway, this is already described in our README.md under section [SETUP](https://github.com/NativeScript/nativescript-dev-appium/blob/master/README.md#setup)
where anybody who read this issue could take a look.
