### ISSUE TITLE
nativescript-dev-appium for chat applications

### ISSUE THREAD

**Issue by NirmalAyyappan** [NativeScript/nativescript-dev-appium#146]
Hi,

I have requirement to test chat application, here the scenario is i need to launch the app in 2 devices and initiate chat b/w those devices and very the message is delivered and verify the message sent.

What i understood from lot of research in internet, i need to initiate 2 appium server with different ports and connect devices to each on of the appium server.

Is it possible to achieve this with nativescript-dev-appium?

If yes, please let me know how to do this

**Comment by SvetoslavTsenov** [comment]
Hi @NirmalAyyappan,

Sorry for delayed answer but I was on a vacation.
As far as I understood your scenario you need to communicate with 2 different devices in a single test which I guess currently is not possible with ns-dev-appium plugin. 
Basically, to be able to do this we will need to be able to initiate multiple driver session not servers.
Anyway, I will try to investigate if the current implementation of the plugin (probably with a few changes in code ) could make this scenario possible and get back to you.

**Comment by selvamrajesh** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'e2e',
1 verbose cli   '--',
1 verbose cli   '--runType',
1 verbose cli   'android19',
1 verbose cli   '--reuseDevice' ]
2 info using npm@6.4.1
3 info using node@v6.4.0
4 verbose run-script [ 'pree2e', 'e2e', 'poste2e' ]
5 info lifecycle @~pree2e: @
6 info lifecycle @~e2e: @
7 verbose lifecycle @~e2e: unsafe-perm in lifecycle true
8 verbose lifecycle @~e2e: PATH: C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Project\JavaScriptApp\node_modules\.bin;C:\Program Files (x86)\Java\jdk1.8.0_131\bin;D:\App\sdk\platform-tools;D:\App\sdk\tools\bin;C:\Program Files\nodejs\;D:\App\sdk\platform-tools;D:\App\sdk\tools;C:\Python27\;C:\Windows\System32;C:\Users\admin\AppData\Roaming\npm
9 verbose lifecycle @~e2e: CWD: D:\Project\JavaScriptApp
10 silly lifecycle @~e2e: Args: [ '/d /s /c',
10 silly lifecycle   'mocha --opts ../config/mocha.opts --recursive e2e --appiumCapsLocation ../config/appium.capabilities.json "--runType" "android19" "--reuseDevice"' ]
11 silly lifecycle @~e2e: Returned: code: 1  signal: null
12 info lifecycle @~e2e: Failed to exec e2e script
13 verbose stack Error: @ e2e: `mocha --opts ../config/mocha.opts --recursive e2e --appiumCapsLocation ../config/appium.capabilities.json "--runType" "android19" "--reuseDevice"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:852:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
14 verbose pkgid @
15 verbose cwd D:\Project\JavaScriptApp
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e" "--" "--runType" "android19" "--reuseDevice"
18 verbose node v6.4.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @ e2e: `mocha --opts ../config/mocha.opts --recursive e2e --appiumCapsLocation ../config/appium.capabilities.json "--runType" "android19" "--reuseDevice"`
22 error Exit status 1
23 error Failed at the @ e2e script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
