### ISSUE TITLE
Current release build seams broken

### ISSUE THREAD

**Issue by mn-martin** [NativeScript/nativescript-dev-appium#21]
With a clean build following the documentation I'm running into following error.

```bash
> tsc -p e2e && mocha --opts ./e2e/config/mocha.opts "--runType" "android"

CONFIG:  { executionPath: '/Users/hettiger/Documents/Projekte/exploreTesting',
  loglevel: false,
  testFolder: 'e2e',
  runType: 'android',
  capsLocation: 'e2e/config',
  isSauceLab: false }
/Users/hettiger/Documents/Projekte/exploreTesting/node_modules/nativescript-dev-appium/index.js:71
    appium = projectAppiumBinary;
           ^

TypeError: Assignment to constant variable.
    at Object.<anonymous> (/Users/hettiger/Documents/Projekte/exploreTesting/node_modules/nativescript-dev-appium/index.js:71:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/hettiger/Documents/Projekte/exploreTesting/e2e/sample-test.e2e.js:37:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/hettiger/Documents/Projekte/exploreTesting/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/hettiger/Documents/Projekte/exploreTesting/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/hettiger/Documents/Projekte/exploreTesting/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/Users/hettiger/Documents/Projekte/exploreTesting/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "e2e" "--" "--runType" "android"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ e2e: `tsc -p e2e && mocha --opts ./e2e/config/mocha.opts "--runType" "android"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ e2e script 'tsc -p e2e && mocha --opts ./e2e/config/mocha.opts "--runType" "android"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p e2e && mocha --opts ./e2e/config/mocha.opts "--runType" "android"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hettiger/Documents/Projekte/exploreTesting/npm-debug.log
```

If I change https://github.com/NativeScript/nativescript-dev-appium/blob/1e3fe40ade121e21780079975ccdf0aaa62925cb/index.js#L44 to `let appium = process.platform === "win32" ? "appium.cmd" : "appium";` everything starts to be working fine.

```bash
node -v && npm -v && tns --version
v6.10.0
3.10.10
3.1.3
cat package.json 
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.exploreTesting",
    "tns-android": {
      "version": "3.1.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.2.0",
    "@angular/common": "~4.2.0",
    "@angular/compiler": "~4.2.0",
    "@angular/core": "~4.2.0",
    "@angular/forms": "~4.2.0",
    "@angular/http": "~4.2.0",
    "@angular/platform-browser": "~4.2.0",
    "@angular/router": "~4.2.0",
    "nativescript-angular": "~4.2.0",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-unit-test-runner": "^0.3.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    "tns-core-modules": "~3.1.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@types/chai": "^4.0.2",
    "@types/mocha": "^2.2.41",
    "@types/node": "^7.0.5",
    "appium": "^1.6.5",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "chai": "^4.1.1",
    "chai-as-promised": "~7.1.1",
    "colors": "^1.1.2",
    "karma": "^1.7.0",
    "karma-chai": "^0.1.0",
    "karma-mocha": "^1.3.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "mocha": "~3.5.0",
    "mocha-junit-reporter": "^1.13.0",
    "mocha-multi": "^0.11.0",
    "nativescript-dev-appium": "^2.0.1",
    "nativescript-dev-typescript": "~0.5.0",
    "tslib": "^1.7.1",
    "typescript": "~2.4.2",
    "wd": "^1.4.0"
  },
  "scripts": {
    "appium": "tsc -p e2e && nativescript-dev-appium",
    "e2e": "tsc -p e2e && mocha --opts ./e2e/config/mocha.opts"
  }
}
```

**Comment by SvetoslavTsenov** [comment]
Hi, @mn-martin. Thaks for the reported issue. This one is already resolved with the next version. We are about to release a new version with a bunch of new features like image processing and etc.

**Comment by mn-martin** [comment]
Thank's for clarification @SvetoslavTsenov I'll close it then 👍
