### ISSUE TITLE
Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started

### ISSUE THREAD

**Issue by pboulch** [NativeScript/nativescript-dev-appium#233]
**Environment**
 - CLI: 5.2.3
 - Cross-platform modules: 5.2.2
 - Android Runtime: 5.2.1
 - iOS Runtime: 5.3.1
 - Plugin(s):

**Describe the bug**
I try to test my Nativescript application but if one test failed, Appium crash with this error : 
```
Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started

[debug] [GENERIC (screensh)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:298:15)
[debug] [GENERIC (screensh)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:489:15)
[debug] [GENERIC (screensh)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)

[debug] [GENERIC (screensh)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)

[debug] [GENERIC (screensh)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)

[debug] [GENERIC (screensh)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)

[debug] [GENERIC (screensh)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22

[debug] [GENERIC (screensh)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)

[debug] [GENERIC (screensh)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[debug] [GENERIC (screensh)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
[debug] [GENERIC (screensh)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)

[debug] [GENERIC (screensh)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [GENERIC (screensh)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)

[debug] [GENERIC (screensh)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [GENERIC (screensh)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7

[debug] [GENERIC (screensh)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)

[debug] [GENERIC (screensh)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)

[debug] [GENERIC (screensh)]     at jsonParser (/usr/local/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:110:7)
[debug] [GENERIC (screensh)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (screensh)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [GENERIC (screensh)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [GENERIC (screensh)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12
```
After a few tests, I think the problem comes from : 
```
afterEach(async function () {
        if (this.currentTest.state === "failed") {
            await driver.logTestArtifacts(this.currentTest.title);
        }
    });
```
Appium is waiting for the driver to take a screenshot but it encounters an error.

**To Reproduce**
```
npm run e2e -- --runType pixel --reuseDevice --cleanApp --verbose
```
**Expected behavior**
The plugin works as expected if I remove 
```
await driver.logTestArtifacts(this.currentTest.title);
```
but then I do not have the screenshots. Is it possible to have them again or is this a a feature that will disappear ?

**Comment by pboulch** [comment]
In fact, I can not do any tests since the application  is not launched on the emulator. When I launch the application : 
```
tns run android
```
it works, but with the test command : 
```
npm run e2e -- --runType pixel --reuseDevice --cleanApp
```
the application does not launch, but the tests are still done. But the method `findElementByAccessibilityId` doesn't work because the application is not launch.
